# permissions for end users to edit policies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: policy-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: policy-controller
    app.kubernetes.io/part-of: policy-controller
    app.kubernetes.io/managed-by: kustomize
  name: policy-editor-role
rules:
- apiGroups:
  - config.stackrox.io.redhat.com
  resources:
  - policies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.stackrox.io.redhat.com
  resources:
  - policies/status
  verbs:
  - get
