---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - config.stackrox.io.redhat.com
  resources:
  - policies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.stackrox.io.redhat.com
  resources:
  - policies/finalizers
  verbs:
  - update
- apiGroups:
  - config.stackrox.io.redhat.com
  resources:
  - policies/status
  verbs:
  - get
  - patch
  - update
